package com.creditease.dao;

import com.creditease.pojo.Proxys;

public interface ProxysMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxys
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxys
     *
     * @mbggenerated
     */
    int insert(Proxys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxys
     *
     * @mbggenerated
     */
    int insertSelective(Proxys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxys
     *
     * @mbggenerated
     */
    Proxys selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxys
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Proxys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxys
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Proxys record);
}